In [2]:
import pandas as pd

#### Pruning the edgelists

In [3]:
total = pd.read_csv("../data/cleaned/total_edgelist.csv")
unique = pd.read_csv("../data/cleaned/unique_edgelist.csv")
repro = pd.read_csv("../data/cleaned/reproducible_edgelist.csv")
# total_hyst = pd.read_csv("../data/cleaned/edgelist_total_hyst.csv")
# unique_hyst = pd.read_csv("../data/cleaned/edgelist_unique_hyst.csv")
# repro_hyst = pd.read_csv("../data/cleaned/edgelist_repro_hyst.csv")
distance = pd.read_csv("../data/cleaned/distance_edgelist.csv")
colony = pd.read_csv("../data/cleaned/colonizer_edgelist.csv")
comcol = pd.read_csv("../data/cleaned/comcol_edgelist.csv")
language = pd.read_csv("../data/cleaned/language_edgelist.csv")
contiguity = pd.read_csv("../data/cleaned/contiguity_edgelist.csv")
rta = pd.read_csv("../data/cleaned/rta_edgelist.csv")
attribute = pd.read_csv("../data/cleaned/attributes.csv")

In [4]:
print(total['iso_o'].nunique())
print(unique['iso_o'].nunique())
print(repro['iso_o'].nunique())
print(distance['iso_o'].nunique())
print(colony['iso_o'].nunique())
print(comcol['iso_o'].nunique())
print(language['iso_o'].nunique())
print(contiguity['iso_o'].nunique())
print(rta['iso_o'].nunique())
print(attribute['iso_o'].nunique())

190
190
190
190
190
190
190
190
190
190

**I am keeping only the countries present in all edgelists and attribute datasets. Hence, I am conducting an inner join process.** 

The steps to prune the edgelists:
>1. Finding out the countries those are not in the attributes edgelist.
>2. Removing those countries from origin column ['iso_o'].
>3. Removing those countries from destination column ['iso_d'].
>4. Checking whether the countries in the origin and destination of an edgelist are same
>5. Cheking whether the number of countries in the origin and destination of an edgelist are same
>6. Replacing the original edgelist saved in the 'cleaned' subfolder of 'data' folder by saving it with the same name as

In [5]:
set(total['iso_o'].unique()) - set(attribute['iso_o'].unique())

set()

In [6]:
set(repro['iso_o'].unique()) - set(attribute['iso_o'].unique())

set()

In [7]:
set(unique['iso_o'].unique()) - set(attribute['iso_o'].unique())

set()

In [8]:
series = [language, distance, contiguity, colony, comcol, total, repro, unique]
remove = ['TWN', 'MSR']

In [9]:
def clean(df):
    return df[~df['iso_o'].isin(remove) & ~df['iso_d'].isin(remove)]
language, distance, contiguity, colony, comcol, total, repro, unique = [clean(df) for df in series]

In [10]:
#series[0]['iso_o'].isin(remove).sum()
#series[0]['iso_d'].isin(remove).sum()

In [11]:
print(set(distance['iso_o'].unique()) - set(attribute['iso_o'].unique()))
print(set(contiguity['iso_o'].unique()) - set(attribute['iso_o'].unique()))
print(set(colony['iso_o'].unique()) - set(attribute['iso_o'].unique()))
print(set(comcol['iso_o'].unique()) - set(attribute['iso_o'].unique()))
print(set(language['iso_o'].unique()) - set(attribute['iso_o'].unique()))

set()
set()
set()
set()
set()

In [12]:
repro.columns

Index(['iso_o', 'iso_d', '1995', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021', '2022', '2023'],
      dtype='object')

As RTA dataset is not available for 2023, I'm removing 2024 from the analysis.

In [13]:
# unique = unique.drop(columns = '2024')
# repro = repro.drop(columns = '2024')

In [14]:
total.to_csv("../data/cleaned/total_edgelist.csv", encoding = 'utf-8', index = False)
unique.to_csv("../data/cleaned/unique_edgelist.csv", encoding = 'utf-8', index = False)
repro.to_csv("../data/cleaned/reproducible_edgelist.csv", encoding = 'utf-8', index = False)

In [15]:
distance.to_csv("../data/cleaned/distance_edgelist.csv", encoding = 'utf-8', index = False)
contiguity.to_csv("../data/cleaned/contiguity_edgelist.csv", encoding = 'utf-8', index = False)
colony.to_csv("../data/cleaned/colonizer_edgelist.csv", encoding = 'utf-8', index = False)
comcol.to_csv("../data/cleaned/comcol_edgelist.csv", encoding = 'utf-8', index = False)
language.to_csv("../data/cleaned/language_edgelist.csv", encoding = 'utf-8', index = False)

* RTA

In [16]:
l = set(rta['iso_o'].unique()) - set(attribute['iso_o'].unique())

In [17]:
len(l)

0

In [18]:
280 - 90

190

In [19]:
rta = rta[~rta['iso_o'].isin(l)]
rta = rta[~rta['iso_d'].isin(l)]

In [20]:
print(rta['iso_o'].nunique())
print(rta['iso_d'].nunique())

190
190

In [21]:
total['iso_o'].nunique()

190

In [22]:
rta.to_csv("../data/cleaned/rta_edgelist.csv", encoding = 'utf-8', index = False)

In [23]:
assert rta['iso_o'].nunique() == total['iso_o'].nunique() == unique['iso_o'].nunique() == repro['iso_o'].nunique() == distance['iso_o'].nunique() == comcol['iso_o'].nunique() == colony['iso_o'].nunique() == language['iso_o'].nunique() == contiguity['iso_o'].nunique() == attribute['iso_o'].nunique()

In [24]:
assert rta['iso_d'].nunique() == total['iso_d'].nunique() == unique['iso_d'].nunique() == repro['iso_d'].nunique() == distance['iso_d'].nunique() == comcol['iso_d'].nunique() == colony['iso_d'].nunique() == language['iso_d'].nunique() == contiguity['iso_d'].nunique()

In [25]:
assert set(rta['iso_d'].unique()) == set(total['iso_d'].unique()) == set(unique['iso_d'].unique()) == set(repro['iso_d'].unique()) == set(distance['iso_d'].unique()) == set(comcol['iso_d'].unique()) == set(colony['iso_d'].unique()) == set(language['iso_d'].unique()) == set(contiguity['iso_d'].unique())

In [26]:
assert set(rta['iso_o'].unique()) == set(total['iso_o'].unique()) == set(unique['iso_o'].unique()) == set(repro['iso_o'].unique()) == set(distance['iso_o'].unique()) == set(comcol['iso_o'].unique()) == set(colony['iso_o'].unique()) == set(language['iso_o'].unique()) == set(contiguity['iso_o'].unique())

In [27]:
print(total['iso_o'].nunique())
print(unique['iso_o'].nunique())
print(repro['iso_o'].nunique())
print(distance['iso_o'].nunique())
print(comcol['iso_o'].nunique())
print(colony['iso_o'].nunique())
print(language['iso_o'].nunique())
print(contiguity['iso_o'].nunique())
print(rta['iso_o'].nunique())
print(attribute['iso_o'].nunique())

190
190
190
190
190
190
190
190
190
190

### Preparing the panel data

**Steps to prepare the panel dataet:**
>1. Removing the year 1999 from attribute2000_2023 dataframe for removing the NaN columns of first differences variables
>2. Renaming the 'time' column to 'TIME_PERIOD" of attributes data to match with the other dataset
>3. Finding out and removing the countries those are present in the long format trade dataset but are not in the attributes dataset from both origin and destination
>4. Renaming the 'OBS_VALUE' column of the respective trade data frame as 'total_tr', 'unique_cultural_tr'and 'reproducible_cultural_tr'
>5. Finding out and removing the countries those are present in the dataset containing all fixed factors (both node and dyad level) but are not in the attributes dataset from both origin and destination
>6. Imputing missing values for the 'development' column of the fixed long data from WDI country classification based on income.
>7. Merging the attributes data with total trade data first as the attributes has highest rows for each observation ['iso_o'] and ordering the columns and naming it as 'panel_total'
>8. Removing 'PRODUCT_HS' and 'ADJUSTMENT' columns from unique cultural trade data and merging with the 'panel_total' on 'iso_o', 'iso_d' and 'TIME_PERIOD', using left joing method and naming the new data as 'panel_total2'
>9. Removing 'PRODUCT_HS' and 'product_count' columns from reproducible cultual trade data and merging with the 'panel_total2' on 'iso_o', 'iso_d' and 'TIME_PERIOD', using left joing method and naming the new data as 'panel_total3'
>10. From Itertools I made a dataframe of all possible country pair for all 24 years that have 190*190*24 rows.
>11. I removed the selfloops from that dataframe with three columns.
>12. I merged it with the subset of the panel_data3 dataframe created at step 7 on 'iso_o', 'iso_d' and 'TIME_PERIOD'
>13. Then I merged 'attribute2000_2023' which is the country level attribute data on 'iso_o' and 'TIME_PERIOD'
>14. Created a copy of the dataframe, renaming all the colum names with suffix '_d', removing the 'iso_o' column
>15. Removing duplicates on `['iso_d', 'TIME_PERIOD']`
>16. Checking that every country appears 24 times (once for every year)
>17. Merging this data on `['iso_d', 'TIME_PERIOD']`
>18. Merging fixed_long data (having node and dyad level fixed factors) with it on 'iso_o' and 'iso_d'
>10. Sanity check steps and saving as csv

In [28]:
total_long = pd.read_csv("../data/cleaned/noncultural.csv")
unique_long = pd.read_csv("../data/cleaned/unique.csv")
repro_long = pd.read_csv("../data/cleaned/reproducible.csv")
fixed_long = pd.read_csv("../data/cleaned/fixed.csv")

In [29]:
print(attribute['iso_o'].nunique())
print(fixed_long['iso_o'].nunique())
print(total_long['iso_o'].nunique())

190
224
204

In [30]:
224 - 190

34

In [31]:
# Renaming the TIME_PERIOD column to year
series1 = [total_long, unique_long, repro_long]
series1 = [df.rename(columns={'TIME_PERIOD': 'year'}) for df in series1]
total_long, unique_long, repro_long = series1

In [32]:
print(set(total_long['iso_o'].unique()) - set(attribute['iso_o'].unique()))
print(set(unique_long['iso_o'].unique()) - set(attribute['iso_o'].unique()))
print(set(repro_long['iso_o'].unique()) - set(attribute['iso_o'].unique()))
print(set(fixed_long['iso_o'].unique()) - set(attribute['iso_o'].unique()))

{'BEL_LUX', 'TLS', 'TWN', 'SACU', 'SCG_F', 'ROU', 'SDN_F', 'PSE', 'SRB', 'SSD', 'WXD', 'COD', 'MSR', 'MNE'}
{'BEL_LUX', 'TLS', 'TWN', 'SACU', 'SCG_F', 'ROU', 'SDN_F', 'PSE', 'SRB', 'SSD', 'WXD', 'COD', 'MSR', 'MNE'}
{'BEL_LUX', 'TLS', 'TWN', 'SACU', 'SCG_F', 'ROU', 'SDN_F', 'PSE', 'SRB', 'SSD', 'WXD', 'COD', 'MSR', 'MNE'}
{'SMR', 'TCA', 'GIB', 'SPM', 'WLF', 'CXR', 'GLP', 'NIU', 'TKL', 'ESH', 'NFK', 'MNP', 'PCN', 'CCK', 'CYM', 'MTQ', 'REU', 'PRI', 'SOM', 'PAL', 'FLK', 'AIA', 'ANT', 'MSR', 'YUG', 'VGB', 'TWN', 'TMP', 'COK', 'GUF', 'SHN', 'ZAR', 'FRO', 'ROM'}

In [33]:
attribute.head(2)

,country,iso_o,year,gdp_pc,trade_ratio,log_gdp_pc,country_id,D_log_gdp_pc
0,Aruba,ABW,1995,35386.859,171.36,10.474096,ABW,NaN
1,Aruba,ABW,1996,34419.430,175.34,10.446377,ABW,-0.027719

In [34]:
set(attribute['year'].unique()) - set(total_long['year'].unique())

set()

In [35]:
attribute = attribute[attribute['year'] != 2024]

In [36]:
total_long = total_long[total_long['year'] != 2024]
unique_long = unique_long[unique_long['year'] != 2024]
repro_long = repro_long[repro_long['year'] != 2024]

In [37]:
print(attribute['year'].unique())

[1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008
 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022
 2023]

In [38]:
assert attribute['year'].nunique() == total_long['year'].nunique() == unique_long['year'].nunique() == repro_long['year'].nunique()

* The number of countries in the long format trade datasets are 201 and the number of countries in the attribute dataset is 190. All the long format trade datasets have the same 11 more countries than the attribute dataset.
* The dyad level time invariant 'fixed' dataset has 34 countries those are not in the attribute dataset.

#### Total trade

In [39]:
remove_from_trade = list(set(total_long['iso_o'].unique()) - set(attribute['iso_o'].unique()))

In [40]:
remove_from_trade

['BEL_LUX',
 'TLS',
 'TWN',
 'SACU',
 'SCG_F',
 'ROU',
 'SDN_F',
 'PSE',
 'SRB',
 'SSD',
 'WXD',
 'COD',
 'MSR',
 'MNE']

In [41]:
total_long = total_long[~total_long['iso_o'].isin(remove_from_trade)]
total_long = total_long[~total_long['iso_d'].isin(remove_from_trade)]

In [42]:
print(total_long['iso_o'].nunique())
print(total_long['iso_d'].nunique())

190
190

In [43]:
total_long.head(3)

,iso_o,iso_d,year,noncultural_trade,product_count,hysteresis_noncultural_trade
0,ABW,AFG,2017,0.069146,10,0.000000
1,ABW,AFG,2018,0.422331,15,0.069146
2,ABW,AFG,2019,0.278743,29,0.443075

#### Unique cultural goods trade

In [44]:
unique_long = unique_long[~unique_long['iso_o'].isin(remove_from_trade)]
unique_long = unique_long[~unique_long['iso_d'].isin(remove_from_trade)]

In [45]:
print(unique_long['iso_o'].nunique())
print(unique_long['iso_d'].nunique())

190
190

In [46]:
unique_long.head(3)

  iso_o iso_d  year    unique  product_count  hysteresis_unique
0   ABW   ARE  2023  0.000113              1           0.000000
1   ABW   AUT  2013  0.002537              2           0.000000
2   ABW   AUT  2014  0.001343              1           0.002537

#### Reproducible cultural goods trade

In [47]:
repro_long = repro_long[~repro_long['iso_o'].isin(remove_from_trade)]
repro_long = repro_long[~repro_long['iso_d'].isin(remove_from_trade)]

In [48]:
print(repro_long['iso_o'].nunique())
print(repro_long['iso_d'].nunique())

190
190

In [49]:
repro_long.head(3)

  iso_o iso_d  year  reproducible  product_count  hysteresis_reproducible
0   ABW   AFG  2019      0.001492              1                 0.000000
1   ABW   ARG  2000      0.000015              1                 0.000000
2   ABW   ARG  2002      0.000121              2                 0.000015

#### Fixed

In [50]:
remove_from_fixed = list(set(fixed_long['iso_o'].unique()) - set(attribute['iso_o'].unique()))

In [51]:
fixed_long = fixed_long[~fixed_long['iso_o'].isin(remove_from_fixed)]
fixed_long = fixed_long[~fixed_long['iso_d'].isin(remove_from_fixed)]

In [52]:
print(fixed_long['iso_o'].nunique())
print(fixed_long['iso_d'].nunique())

190
190

In [53]:
#fixed_long[fixed_long['development'].isna()]

In [54]:
fixed_long.loc[fixed_long['country'] == 'Bermuda', 'development'] = 1
fixed_long.loc[fixed_long['country'] == 'Cuba', 'development'] = 0
fixed_long.loc[fixed_long['country'] == 'French Polynesia', 'development'] = 1
fixed_long.loc[fixed_long['country'] == 'Greenland', 'development'] = 1
fixed_long.loc[fixed_long['country'] == 'New Caledonia', 'development'] = 1

### panel data

In [55]:
panel_total = attribute.merge(total_long, on = ['iso_o', 'year'])

In [56]:
print(total_long.groupby(['iso_o', 'iso_d']).ngroups)
print(panel_total.groupby(['iso_o', 'iso_d']).ngroups)

34144
34144

In [57]:
print(total_long['iso_o'].nunique(), total_long['iso_d'].nunique(), total_long['year'].nunique())
print(panel_total['iso_o'].nunique(), panel_total['iso_d'].nunique(), panel_total['year'].nunique())
print(attribute['iso_o'].nunique(), attribute['year'].nunique())

190 190 29
190 190 29
190 29

In [58]:
panel_total.head(2)

,country,iso_o,year,gdp_pc,trade_ratio,log_gdp_pc,country_id,D_log_gdp_pc,iso_d,noncultural_trade,product_count,hysteresis_noncultural_trade
0,Aruba,ABW,1995,35386.859,171.36,10.474096,ABW,NaN,ALB,0.002297,1,0.0
1,Aruba,ABW,1995,35386.859,171.36,10.474096,ABW,NaN,BGR,0.169382,1,0.0

In [59]:
panel_total = panel_total[['country', 'iso_o', 'iso_d', 'year', 'noncultural_trade', 'hysteresis_noncultural_trade', 'gdp_pc', 'log_gdp_pc', 'D_log_gdp_pc','trade_ratio']]

In [60]:
panel_total.head(3)

,country,iso_o,iso_d,year,noncultural_trade,hysteresis_noncultural_trade,gdp_pc,log_gdp_pc,D_log_gdp_pc,trade_ratio
0,Aruba,ABW,ALB,1995,0.002297,0.0,35386.859,10.474096,NaN,171.36
1,Aruba,ABW,BGR,1995,0.169382,0.0,35386.859,10.474096,NaN,171.36
2,Aruba,ABW,BHS,1995,0.099408,0.0,35386.859,10.474096,NaN,171.36

**Merging the previous data with unique cultural goods trade data**

In [61]:
unique_long.head(2)

  iso_o iso_d  year    unique  product_count  hysteresis_unique
0   ABW   ARE  2023  0.000113              1                0.0
1   ABW   AUT  2013  0.002537              2                0.0

In [62]:
unique_clean = unique_long.drop(columns = 'product_count').drop_duplicates() #removing these two columns

In [63]:
unique_clean.head(2)

  iso_o iso_d  year    unique  hysteresis_unique
0   ABW   ARE  2023  0.000113                0.0
1   ABW   AUT  2013  0.002537                0.0

In [64]:
panel_total2 = panel_total.merge(unique_clean, on = ['iso_o', 'iso_d', 'year'], how = 'left')

In [65]:
panel_total2.head(2)

,country,iso_o,iso_d,year,noncultural_trade,hysteresis_noncultural_trade,gdp_pc,log_gdp_pc,D_log_gdp_pc,trade_ratio,unique,hysteresis_unique
0,Aruba,ABW,ALB,1995,0.002297,0.0,35386.859,10.474096,NaN,171.36,NaN,NaN
1,Aruba,ABW,BGR,1995,0.169382,0.0,35386.859,10.474096,NaN,171.36,NaN,NaN

In [66]:
# sanity check
panel_total2[(panel_total2['iso_o'] == 'ABW') & (panel_total2['iso_d'] == 'AGO') & (panel_total2['year'] == 2014)]

,country,iso_o,iso_d,year,noncultural_trade,hysteresis_noncultural_trade,gdp_pc,log_gdp_pc,D_log_gdp_pc,trade_ratio,unique,hysteresis_unique
1447,Aruba,ABW,AGO,2014,0.039386,1.421557,35746.859,10.484218,0.003505,156.49001,NaN,NaN

In [67]:
panel_total2 = panel_total2[['country', 'iso_o', 'iso_d', 'year', 'noncultural_trade', 'hysteresis_noncultural_trade', 'unique', 'hysteresis_unique','gdp_pc', 'log_gdp_pc', 'D_log_gdp_pc','trade_ratio']]

In [68]:
print(unique_long.groupby(['iso_o', 'iso_d']).ngroups)
print(panel_total2.groupby(['iso_o', 'iso_d']).ngroups)

16645
34144

In [69]:
print(unique_long['iso_o'].nunique(), unique_long['iso_d'].nunique(), unique_long['year'].nunique())
print(panel_total2['iso_o'].nunique(), panel_total2['iso_d'].nunique(), panel_total2['year'].nunique())

190 190 29
190 190 29

**Merging the previous data with reproducible goods trade data**

In [70]:
repro_long.head(2)

  iso_o iso_d  year  reproducible  product_count  hysteresis_reproducible
0   ABW   AFG  2019      0.001492              1                      0.0
1   ABW   ARG  2000      0.000015              1                      0.0

In [71]:
repro_clean = repro_long.drop(columns = 'product_count').drop_duplicates() #removing these two columns

In [72]:
panel_total3 = panel_total2.merge(repro_clean, on = ['iso_o', 'iso_d', 'year'], how='left')

In [73]:
panel_total3 = panel_total3[['country', 'iso_o', 'iso_d', 'year', 'noncultural_trade', 'hysteresis_noncultural_trade', 'unique', 'hysteresis_unique','reproducible','hysteresis_reproducible','gdp_pc', 'log_gdp_pc', 'D_log_gdp_pc','trade_ratio']]

In [74]:
# sanity check
panel_total3[(panel_total3['iso_o'] == 'ABW') & (panel_total3['iso_d'] == 'AGO') & (panel_total3['year'] == 2014)]

,country,iso_o,iso_d,year,noncultural_trade,hysteresis_noncultural_trade,unique,hysteresis_unique,reproducible,hysteresis_reproducible,gdp_pc,log_gdp_pc,D_log_gdp_pc,trade_ratio
1447,Aruba,ABW,AGO,2014,0.039386,1.421557,NaN,NaN,NaN,NaN,35746.859,10.484218,0.003505,156.49001

In [75]:
print(repro_long['iso_o'].nunique(), repro_long['iso_d'].nunique(), repro_long['year'].nunique())
print(panel_total3['iso_o'].nunique(), panel_total3['iso_d'].nunique(), panel_total3['year'].nunique())

190 190 29
190 190 29

In [76]:
rta_long = pd.read_csv("../data/cleaned/rta_long.csv")

In [77]:
rta_long.head(3)

  iso_o iso_d  year  rta
0   ABW   AFG  1995    0
1   ABW   AFG  1996    0
2   ABW   AFG  1997    0

In [78]:
panel_total4 = panel_total3.merge(rta_long, on = ['iso_o', 'iso_d', 'year'], how='left')

In [79]:
panel_total4.head(2)

,country,iso_o,iso_d,year,noncultural_trade,hysteresis_noncultural_trade,unique,hysteresis_unique,reproducible,hysteresis_reproducible,gdp_pc,log_gdp_pc,D_log_gdp_pc,trade_ratio,rta
0,Aruba,ABW,ALB,1995,0.002297,0.0,NaN,NaN,NaN,NaN,35386.859,10.474096,NaN,171.36,0
1,Aruba,ABW,BGR,1995,0.169382,0.0,NaN,NaN,NaN,NaN,35386.859,10.474096,NaN,171.36,0

In [80]:
panel_total4_tr = panel_total4[['iso_o', 'iso_d', 'year', 'noncultural_trade',
       'hysteresis_noncultural_trade', 'unique', 'hysteresis_unique',
       'reproducible', 'hysteresis_reproducible', 'rta' ]]

In [81]:
import itertools

In [82]:
panel_total4_tr.columns

Index(['iso_o', 'iso_d', 'year', 'noncultural_trade',
       'hysteresis_noncultural_trade', 'unique', 'hysteresis_unique',
       'reproducible', 'hysteresis_reproducible', 'rta'],
      dtype='object')

In [83]:
country_list = panel_total4['iso_o'].unique()
print(len(country_list))
years = list(range(1995, 2024))
panel_df = pd.MultiIndex.from_product([country_list, country_list, years], names=['iso_o', 'iso_d', 'year'])
panel_df_blank = panel_df.to_frame(index=False)

190

In [84]:
(190*190 - 190)*29

1041390

In [85]:
panel_df_blank['year'].nunique()

29

In [86]:
panel_df_blank.shape

(1046900, 3)

In [87]:
panel_df_blank = panel_df_blank[panel_df_blank['iso_o'] != panel_df_blank['iso_d']]

In [88]:
only_trade = panel_df_blank.merge(panel_total4_tr, on = ['iso_o', 'iso_d', 'year'], how = 'left')

In [89]:
assert only_trade.shape[0] == panel_df_blank.shape[0]

In [90]:
missing_value_columns = ['noncultural_trade','hysteresis_noncultural_trade', 'unique', 'hysteresis_unique','reproducible', 'hysteresis_reproducible']

In [91]:
only_trade[missing_value_columns] = only_trade[missing_value_columns].fillna(0)

In [92]:
#print(only_trade[(only_trade['iso_o'] == 'BGD') & (only_trade['iso_d'] == 'IND')])

In [93]:
trade_time_series_attribute = only_trade.merge(attribute, on = ['iso_o', 'year'], how = 'left')

In [94]:
assert only_trade.shape[0] == panel_df_blank.shape[0] == trade_time_series_attribute.shape[0]

In [95]:
assert attribute['iso_o'].nunique() == only_trade['iso_o'].nunique() ==  panel_df_blank['iso_o'].nunique() == trade_time_series_attribute['iso_o'].nunique()

In [96]:
trade_time_series_attribute.head(2)

,iso_o,iso_d,year,noncultural_trade,hysteresis_noncultural_trade,unique,hysteresis_unique,reproducible,hysteresis_reproducible,rta,country,gdp_pc,trade_ratio,log_gdp_pc,country_id,D_log_gdp_pc
0,ABW,AFG,1995,0.0,0.0,0.0,0.0,0.0,0.0,NaN,Aruba,35386.859,171.36,10.474096,ABW,NaN
1,ABW,AFG,1996,0.0,0.0,0.0,0.0,0.0,0.0,NaN,Aruba,34419.430,175.34,10.446377,ABW,-0.027719

In [97]:
trade_time_series_attribute.columns

Index(['iso_o', 'iso_d', 'year', 'noncultural_trade',
       'hysteresis_noncultural_trade', 'unique', 'hysteresis_unique',
       'reproducible', 'hysteresis_reproducible', 'rta', 'country', 'gdp_pc',
       'trade_ratio', 'log_gdp_pc', 'country_id', 'D_log_gdp_pc'],
      dtype='object')

In [98]:
trade_time_series_attribute['D_log_gdp_pc'] = trade_time_series_attribute['D_log_gdp_pc'].fillna(0)

In [99]:
trade_time_series_attribute[['gdp_pc', 'trade_ratio','log_gdp_pc',	'D_log_gdp_pc']].isnull().mean()

gdp_pc          0.0
trade_ratio     0.0
log_gdp_pc      0.0
D_log_gdp_pc    0.0
dtype: float64

In [100]:
#raise SystemExit("Stop!")

In [101]:
trade_time_series_attribute =  trade_time_series_attribute.merge(fixed_long, on = ['iso_o', 'iso_d'], how = 'left')

In [102]:
trade_time_series_attribute.columns

Index(['iso_o', 'iso_d', 'year', 'noncultural_trade',
       'hysteresis_noncultural_trade', 'unique', 'hysteresis_unique',
       'reproducible', 'hysteresis_reproducible', 'rta', 'country_x', 'gdp_pc',
       'trade_ratio', 'log_gdp_pc', 'country_id', 'D_log_gdp_pc', 'contig',
       'comlang_off', 'colony', 'comcol', 'dist', 'log_dist', 'country_y',
       'landlocked', 'continent', 'lat', 'lon', 'langoff_1', 'colonizer1',
       'category', 'development'],
      dtype='object')

In [103]:
trade_time_series_attribute = trade_time_series_attribute.drop(columns = ['country_y', 'country_id'])
trade_time_series_attribute = trade_time_series_attribute.rename(columns = {'country_x': 'country'})

In [104]:
trade_time_series_attribute.head(2)

,iso_o,iso_d,year,noncultural_trade,hysteresis_noncultural_trade,unique,hysteresis_unique,reproducible,hysteresis_reproducible,rta,...,dist,log_dist,landlocked,continent,lat,lon,langoff_1,colonizer1,category,development
0,ABW,AFG,1995,0.0,0.0,0.0,0.0,0.0,0.0,NaN,...,13257.81,9.492342,0,America,12.55,-70.099998,Dutch,NLD,Emerging and Developing Economies,0.0
1,ABW,AFG,1996,0.0,0.0,0.0,0.0,0.0,0.0,NaN,...,13257.81,9.492342,0,America,12.55,-70.099998,Dutch,NLD,Emerging and Developing Economies,0.0

#### Creating variables for destination countries using a copy of the original dataset

In [106]:
partner_attributes = trade_time_series_attribute.copy()

In [107]:
partner_attributes.columns

Index(['iso_o', 'iso_d', 'year', 'noncultural_trade',
       'hysteresis_noncultural_trade', 'unique', 'hysteresis_unique',
       'reproducible', 'hysteresis_reproducible', 'rta', 'country', 'gdp_pc',
       'trade_ratio', 'log_gdp_pc', 'D_log_gdp_pc', 'contig', 'comlang_off',
       'colony', 'comcol', 'dist', 'log_dist', 'landlocked', 'continent',
       'lat', 'lon', 'langoff_1', 'colonizer1', 'category', 'development'],
      dtype='object')

In [108]:
#removing all dyad level factors
partner_attributes = partner_attributes.drop(columns = ['iso_d', 'noncultural_trade','hysteresis_noncultural_trade', 'unique', 'hysteresis_unique',
'reproducible', 'hysteresis_reproducible', 'rta', 'contig', 'comlang_off','colony', 'comcol', 'dist', 'log_dist', 'lat', 'lon'])

In [109]:
destination_attributes = {'iso_o': 'iso_d', 'country': 'country_d', 'gdp_pc': 'gdp_pc_d', 'trade_ratio': 'trade_ratio_d', 'log_gdp_pc': 'log_gdp_pc_d',
 'D_log_gdp_pc':'D_log_gdp_pc_d', 'landlocked': 'landlocked_d', 'continent': 'continent_d', 'langoff_1': 'langoff_1_d','colonizer1': 'colonizer1_d', 'category': 'category_d','development': 'development_d',
'colonizer1': 'colonizer1_d'}

In [110]:
partner_attributes = partner_attributes.rename(columns = destination_attributes)

In [111]:
partner_attributes.head(2)

,iso_d,year,country_d,gdp_pc_d,trade_ratio_d,log_gdp_pc_d,D_log_gdp_pc_d,landlocked_d,continent_d,langoff_1_d,colonizer1_d,category_d,development_d
0,ABW,1995,Aruba,35386.859,171.36,10.474096,0.000000,0,America,Dutch,NLD,Emerging and Developing Economies,0.0
1,ABW,1996,Aruba,34419.430,175.34,10.446377,-0.027719,0,America,Dutch,NLD,Emerging and Developing Economies,0.0

In [112]:
partner_attributes.columns

Index(['iso_d', 'year', 'country_d', 'gdp_pc_d', 'trade_ratio_d',
       'log_gdp_pc_d', 'D_log_gdp_pc_d', 'landlocked_d', 'continent_d',
       'langoff_1_d', 'colonizer1_d', 'category_d', 'development_d'],
      dtype='object')

In [113]:
search_duplicate_row = ['iso_d', 'year']

In [114]:
partner_attributes_duplicate = partner_attributes.duplicated(subset = search_duplicate_row,  keep = 'last')

In [115]:
partner_attributes_final = partner_attributes[~partner_attributes_duplicate]

In [116]:
assert partner_attributes_final.shape[0] == attribute.shape[0]

In [117]:
complete = trade_time_series_attribute.merge(partner_attributes_final, on = ['iso_d', 'year'], how = 'left')

In [118]:
complete.shape

(1041390, 40)

In [119]:
complete.columns

Index(['iso_o', 'iso_d', 'year', 'noncultural_trade',
       'hysteresis_noncultural_trade', 'unique', 'hysteresis_unique',
       'reproducible', 'hysteresis_reproducible', 'rta', 'country', 'gdp_pc',
       'trade_ratio', 'log_gdp_pc', 'D_log_gdp_pc', 'contig', 'comlang_off',
       'colony', 'comcol', 'dist', 'log_dist', 'landlocked', 'continent',
       'lat', 'lon', 'langoff_1', 'colonizer1', 'category', 'development',
       'country_d', 'gdp_pc_d', 'trade_ratio_d', 'log_gdp_pc_d',
       'D_log_gdp_pc_d', 'landlocked_d', 'continent_d', 'langoff_1_d',
       'colonizer1_d', 'category_d', 'development_d'],
      dtype='object')

In [120]:
s = complete.columns

In [121]:
len(s)

40

In [122]:
complete[['country', 'country_d']].head(3)

  country    country_d
0   Aruba  Afghanistan
1   Aruba  Afghanistan
2   Aruba  Afghanistan

In [123]:
complete['rta'].dtypes

dtype('float64')

In [124]:
complete['rta'].value_counts(dropna=False)

rta
0.0    569161
NaN    304106
1.0    168123
Name: count, dtype: int64

In [125]:
complete = complete.fillna(0)

In [126]:
assert complete.shape[0]== only_trade.shape[0] == panel_df_blank.shape[0] == trade_time_series_attribute.shape[0]

In [128]:
print(complete.duplicated(subset=['iso_o', 'iso_d', 'year']).any())

False

In [133]:
print(complete['iso_o'].nunique())
print(complete['iso_d'].nunique())
print(complete['year'].nunique())
print(complete['log_gdp_pc'].nunique())
print(complete['D_log_gdp_pc'].nunique())
print(complete['trade_ratio'].nunique())
print(complete['log_dist'].nunique())
print(complete.groupby(['iso_o', 'iso_d']).ngroups) #190*190 is 36100 possible dyads while removing 190 self loops make it (36100- 190) = 35910 dyads
print(complete.shape)

190
190
29
5306
5031
4007
17927
35910
(1041390, 40)

In [134]:
complete.columns

Index(['iso_o', 'iso_d', 'year', 'noncultural_trade',
       'hysteresis_noncultural_trade', 'unique', 'hysteresis_unique',
       'reproducible', 'hysteresis_reproducible', 'rta', 'country', 'gdp_pc',
       'trade_ratio', 'log_gdp_pc', 'D_log_gdp_pc', 'contig', 'comlang_off',
       'colony', 'comcol', 'dist', 'log_dist', 'landlocked', 'continent',
       'lat', 'lon', 'langoff_1', 'colonizer1', 'category', 'development',
       'country_d', 'gdp_pc_d', 'trade_ratio_d', 'log_gdp_pc_d',
       'D_log_gdp_pc_d', 'landlocked_d', 'continent_d', 'langoff_1_d',
       'colonizer1_d', 'category_d', 'development_d'],
      dtype='object')

In [ ]:
# 34782/2 = 17391 #So the unique value of country pair distance column is almost near half of the number of total unique dyads in the data.

In [135]:
complete['dyad_id'] = complete['iso_o'] + '-' + complete['iso_d']

In [136]:
complete.to_csv("../data/cleaned/panel_complete.csv", encoding = 'utf-8', index = False)

In [ ]:
#raise SystemExit("Stop!")

### Adding node level fixed data with node attribute data sets
steps:
>1. Merging the attributeYEAR data with the nodal_fixed data for every year starting from 2000 and ending at 2023
>2. Looking for missing value in the 'category' column and manually impute 1 for developed and 0 for developing to the 'development' column based on WDI income categories. If WDI classifies the countru with hign income, then I am considering it as developed and 0 otherwise.
>3. The Stata do file produces lagged values of GDP per capita and GDP variables and adds to the long format attribute dataset. To add those lag values to the year level attributeYEAR datasets, we first rename those variables to their lowercase so that they match the stata processed dataset.
>4. Then the long format dataset is separated into 24 different dataframes and merged with the corresponding attributeYEAR dataset on the 'iso_o' column.
>5. Saving with the same name as attributeYEAR.csv, so that no few data file is created and the attribute for each year has the fixed factor columns

In [160]:
#attributes = {f"at{year}": pd.read_csv(f"../data/cleaned/attribute{year}.csv") for year in range(2000, 2024)}

In [177]:
node_fix = pd.read_csv("../data/cleaned/nodal_fixed.csv")

In [178]:
node_fix.head(2)

,iso_o,country,landlocked,continent,lat,lon,langoff_1,colonizer1,category,development
0,AND,Andorra,0,Europe,42.500000,1.500000,Catalan,NaN,Advanced Economies,1.0
1,ARE,United Arab Emirates,0,Asia,24.466667,54.416668,Arabic,GBR,Emerging and Developing Economies,0.0

In [179]:
m = set(node_fix['iso_o'].unique()) - set(attribute['iso_o'].unique())
node_fix = node_fix[~node_fix['iso_o'].isin(m)]

In [180]:
node_fix['iso_o'].nunique()

190

In [181]:
set(node_fix['iso_o'].unique()) - set(attribute['iso_o'].unique())

set()

In [182]:
node_fix = node_fix.reset_index(drop = True)

In [183]:
node_fix.columns

Index(['iso_o', 'country', 'landlocked', 'continent', 'lat', 'lon',
       'langoff_1', 'colonizer1', 'category', 'development'],
      dtype='object')

In [184]:
attribute.columns

Index(['country', 'iso_o', 'year', 'gdp_pc', 'trade_ratio', 'log_gdp_pc',
       'country_id', 'D_log_gdp_pc'],
      dtype='object')

In [185]:
dev_map = {'Bermuda': 1, 'Cuba': 0, 'French Polynesia': 1, 'Greenland': 1,'New Caledonia': 1}

In [186]:
attributes = {f'attribute{year}': attribute[attribute['year'] == year].copy() for year in range(1995, 2025)}

In [190]:
attributes['attribute1996'].head(2)

,country,iso_o,year,gdp_pc,trade_ratio,log_gdp_pc,country_id,D_log_gdp_pc
1,Aruba,ABW,1996,34419.430,175.340000,10.446377,ABW,-0.027719
31,Afghanistan,AFG,1996,15850.788,69.986649,9.670975,AFG,0.019962

In [192]:
for name, dataframe in attributes.items():
    dataframe = dataframe.merge(node_fix, on = 'iso_o', how = 'left', suffixes = ('', '_node'))
    dataframe.loc[dataframe['country'].isin(dev_map), 'development'] = dataframe['country'].map(dev_map)
    dataframe = dataframe.drop(columns = ['country_id', 'country_node'])
    attributes[name] = dataframe

In [193]:
attributes['attribute1995'].columns

Index(['country', 'iso_o', 'year', 'gdp_pc', 'trade_ratio', 'log_gdp_pc',
       'D_log_gdp_pc', 'landlocked', 'continent', 'lat', 'lon', 'langoff_1',
       'colonizer1', 'category', 'development'],
      dtype='object')

In [195]:
attributes['attribute1996'].head(2)

,country,iso_o,year,gdp_pc,trade_ratio,log_gdp_pc,D_log_gdp_pc,landlocked,continent,lat,lon,langoff_1,colonizer1,category,development
0,Aruba,ABW,1996,34419.430,175.340000,10.446377,-0.027719,0,America,12.550000,-70.099998,Dutch,NLD,Emerging and Developing Economies,0.0
1,Afghanistan,AFG,1996,15850.788,69.986649,9.670975,0.019962,1,Asia,34.516666,69.199997,Persian,NaN,Emerging and Developing Economies,0.0

In [196]:
for year in range(1995, 2024):
    attributes[f'attribute{year}'].to_csv(f"../data/cleaned/attribute{year}.csv", encoding="utf-8", index=False)

In [ ]:
#at2012[at2012['Country'] == 'New Caledonia']